---
name: Update docs

on:
  push:
    branches:
      - release-please--branches--main

permissions: read-all

jobs:
  docs:
    # update docs after merge back to develop
    name: Auto update terraform docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Generate TF docs
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          find-dir: .
          git-commit-message: "docs: auto update terraform docs"
          git-push: true
